### ISSUE TITLE
Empty incoming changes not recognised

### ISSUE THREAD

**Issue by d4nc00per** [pprice/vscode-better-merge#13]
![merge-bug](https://cloud.githubusercontent.com/assets/5233036/21228877/6eb93778-c2d7-11e6-884d-6dc2c9125592.png)

**Comment by pprice** [comment]
Thanks for the bug report, I'll look into this 👍

**Comment by capaj** [comment]
I also had this issue on vscode: ```Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0```

**Comment by Bigous** [comment]
Greate extension!
Empty current not handled too.
![image](https://cloud.githubusercontent.com/assets/6886560/21767866/9e5e6f22-d65d-11e6-9dc4-3a15d7087967.png)

**Comment by blopez2010** [comment]
When do you have plans to fix this issue??? it would really helpful!!

**Comment by GaryBoone** [comment]
I also just observed this problem. 

Otherwise, excellent tool.

**Comment by GaryBoone** [comment]
I don't know this environment well enough to do a fix, test, and pull request, but it looks like the problem is in [Line 19 of mergeConflictParser.ts](https://github.com/pprice/vscode-better-merge/blob/master/src/services/mergeConflictParser.ts#L19):

const conflictMatcher = /(<<<<<<< (.+)\r?\n)^((.*\s)+?)(^=======\r?\n)^((.*\s)+?)(^>>>>>>> (.+)$)/mg;

The regular expression looks for a line of text between each of the markers. In the case of insertions or deletions, there isn't such a line for one of the change lines.
