### ISSUE TITLE
Allow editing in "compare" editor

### ISSUE THREAD

**Issue by rossnichols** [pprice/vscode-better-merge#25]
My normal workflow for resolving merges is to edit the incoming change until it has what I want, then select "accept incoming". It would be nice if the "compare" view allowed editing.

**Comment by pprice** [comment]
Thanks @rossnichols, I think this is good idea. 

cc @eamodio - do you know if there are any flags to make this possible when opening up the vscode.diff? Couple of things I'm thinking: 

 - Sync changes between the compare view and the origin document (sounds expensive) 
 - Open a "regular" compare, and jump to the appropriate merge conflict block.

**Comment by eamodio** [comment]
Heh -- I really wanted something like this when I added the compare feature. Unfortunately I couldn't come up with a great way of dealing with it.

Here are the issues, as I see them.

- Because the compare opens the text blocks via a `TextDocumentContentProvider` (basically a "virtual" document) it is read-only -- as far as I know the vscode api doesn't have any way to open a non-readonly virtual document cc @jrieken
    - Instead of using a `TextDocumentContentProvider` we *could* use temporary files for each side, but that would be far more expensive
- Assuming we've resolved the above, then we need to somehow capture any changes and sync them back with the original merge file block
    - We could handle this by having these new temp files have their own uri scheme that we could have a code lens provider registered for -- to provide the actions of "accepting" the changes and syncing them back to the original file. A little bit tricky but certainly doable
- Might also need to handle the case if the user opens a compare more than once
- Then there is the worry about what happens if the user changes the original file while the compare is still open -- should be able to handle it with watching the original for changes

Another option is one I sort of outlined https://github.com/pprice/vscode-better-merge/pull/22#issuecomment-298953112

So instead of 2 temp files with just the conflict -- you could have a diff of 2 temp files with the left-side looking like you accepted all current changes, and the right-side looking like you accepted all incoming changes. This still has many of the issues as above, but you don't have to worry about syncing -- just a wholesale replacement of the original file

Honestly, while I too would really like this feature, I'm not convinced it is worth the complexities involved. Although if vscode supported editable "virtual" documents via `TextDocumentContentProvider` it might tip the scale.

@pprice I'm not following what you mean here
> Open a "regular" compare, and jump to the appropriate merge conflict block.

**Comment by pprice** [comment]
Thanks @eamodio! 

Yeah just did some quick reading, virtual document editing is not supported. 😞 

RE:
> Open a "regular" compare, and jump to the appropriate merge conflict block.

This is what you were talking about in #22, just diff two actual files, and this should be editable.

I agree with you, this is sounding complicated and vscode hasn't really got the API surface area to enable this.  I'll leave this open and see if others can chime in with other ideas.

**Comment by pprice** [comment]
Closing.
